// Code generated by yo. DO NOT EDIT.
// Package models contains the types.
package models

import (
	"context"
	"fmt"
	"time"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/iterator"
	"google.golang.org/grpc/codes"
)

// Goal represents a row from 'Goals'.
type Goal struct {
	GoalID      string             `spanner:"GoalId" json:"GoalId"`           // GoalId
	UserID      string             `spanner:"UserId" json:"UserId"`           // UserId
	Name        string             `spanner:"Name" json:"Name"`               // Name
	Description spanner.NullString `spanner:"Description" json:"Description"` // Description
	Status      string             `spanner:"Status" json:"Status"`           // Status
	CreatedAt   time.Time          `spanner:"CreatedAt" json:"CreatedAt"`     // CreatedAt
	UpdatedAt   time.Time          `spanner:"UpdatedAt" json:"UpdatedAt"`     // UpdatedAt
}

func GoalPrimaryKeys() []string {
	return []string{
		"GoalId",
	}
}

func GoalColumns() []string {
	return []string{
		"GoalId",
		"UserId",
		"Name",
		"Description",
		"Status",
		"CreatedAt",
		"UpdatedAt",
	}
}

func GoalWritableColumns() []string {
	return []string{
		"GoalId",
		"UserId",
		"Name",
		"Description",
		"Status",
		"CreatedAt",
		"UpdatedAt",
	}
}

func (g *Goal) columnsToPtrs(cols []string, customPtrs map[string]interface{}) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		if val, ok := customPtrs[col]; ok {
			ret = append(ret, val)
			continue
		}

		switch col {
		case "GoalId":
			ret = append(ret, &g.GoalID)
		case "UserId":
			ret = append(ret, &g.UserID)
		case "Name":
			ret = append(ret, &g.Name)
		case "Description":
			ret = append(ret, &g.Description)
		case "Status":
			ret = append(ret, &g.Status)
		case "CreatedAt":
			ret = append(ret, &g.CreatedAt)
		case "UpdatedAt":
			ret = append(ret, &g.UpdatedAt)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}
	return ret, nil
}

func (g *Goal) columnsToValues(cols []string) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		switch col {
		case "GoalId":
			ret = append(ret, g.GoalID)
		case "UserId":
			ret = append(ret, g.UserID)
		case "Name":
			ret = append(ret, g.Name)
		case "Description":
			ret = append(ret, g.Description)
		case "Status":
			ret = append(ret, g.Status)
		case "CreatedAt":
			ret = append(ret, g.CreatedAt)
		case "UpdatedAt":
			ret = append(ret, g.UpdatedAt)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}

	return ret, nil
}

// newGoal_Decoder returns a decoder which reads a row from *spanner.Row
// into Goal. The decoder is not goroutine-safe. Don't use it concurrently.
func newGoal_Decoder(cols []string) func(*spanner.Row) (*Goal, error) {
	customPtrs := map[string]interface{}{}

	return func(row *spanner.Row) (*Goal, error) {
		var g Goal
		ptrs, err := g.columnsToPtrs(cols, customPtrs)
		if err != nil {
			return nil, err
		}

		if err := row.Columns(ptrs...); err != nil {
			return nil, err
		}

		return &g, nil
	}
}

// Insert returns a Mutation to insert a row into a table. If the row already
// exists, the write or transaction fails.
func (g *Goal) Insert(ctx context.Context) *spanner.Mutation {
	values, _ := g.columnsToValues(GoalWritableColumns())
	return spanner.Insert("Goals", GoalWritableColumns(), values)
}

// Update returns a Mutation to update a row in a table. If the row does not
// already exist, the write or transaction fails.
func (g *Goal) Update(ctx context.Context) *spanner.Mutation {
	values, _ := g.columnsToValues(GoalWritableColumns())
	return spanner.Update("Goals", GoalWritableColumns(), values)
}

// InsertOrUpdate returns a Mutation to insert a row into a table. If the row
// already exists, it updates it instead. Any column values not explicitly
// written are preserved.
func (g *Goal) InsertOrUpdate(ctx context.Context) *spanner.Mutation {
	values, _ := g.columnsToValues(GoalWritableColumns())
	return spanner.InsertOrUpdate("Goals", GoalWritableColumns(), values)
}

// UpdateColumns returns a Mutation to update specified columns of a row in a table.
func (g *Goal) UpdateColumns(ctx context.Context, cols ...string) (*spanner.Mutation, error) {
	// add primary keys to columns to update by primary keys
	colsWithPKeys := append(cols, GoalPrimaryKeys()...)

	values, err := g.columnsToValues(colsWithPKeys)
	if err != nil {
		return nil, newErrorWithCode(codes.InvalidArgument, "Goal.UpdateColumns", "Goals", err)
	}

	return spanner.Update("Goals", colsWithPKeys, values), nil
}

// FindGoal gets a Goal by primary key
func FindGoal(ctx context.Context, db YORODB, goalID string) (*Goal, error) {
	key := spanner.Key{goalID}
	row, err := db.ReadRow(ctx, "Goals", key, GoalColumns())
	if err != nil {
		return nil, newError("FindGoal", "Goals", err)
	}

	decoder := newGoal_Decoder(GoalColumns())
	g, err := decoder(row)
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "FindGoal", "Goals", err)
	}

	return g, nil
}

// ReadGoal retrieves multiples rows from Goal by KeySet as a slice.
func ReadGoal(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*Goal, error) {
	var res []*Goal

	decoder := newGoal_Decoder(GoalColumns())

	rows := db.Read(ctx, "Goals", keys, GoalColumns())
	err := rows.Do(func(row *spanner.Row) error {
		g, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, g)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadGoal", "Goals", err)
	}

	return res, nil
}

// Delete deletes the Goal from the database.
func (g *Goal) Delete(ctx context.Context) *spanner.Mutation {
	values, _ := g.columnsToValues(GoalPrimaryKeys())
	return spanner.Delete("Goals", spanner.Key(values))
}

// FindGoalsByUserIDCreatedAt retrieves multiple rows from 'Goals' as a slice of Goal.
//
// Generated from index 'GoalsByUserIdCreatedAt'.
func FindGoalsByUserIDCreatedAt(ctx context.Context, db YORODB, userID string, createdAt time.Time) ([]*Goal, error) {
	const sqlstr = "SELECT " +
		"GoalId, UserId, Name, Description, Status, CreatedAt, UpdatedAt " +
		"FROM Goals@{FORCE_INDEX=GoalsByUserIdCreatedAt} " +
		"WHERE UserId = @param0 AND CreatedAt = @param1"

	stmt := spanner.NewStatement(sqlstr)
	stmt.Params["param0"] = userID
	stmt.Params["param1"] = createdAt

	decoder := newGoal_Decoder(GoalColumns())

	// run query
	YOLog(ctx, sqlstr, userID, createdAt)
	iter := db.Query(ctx, stmt)
	defer iter.Stop()

	// load results
	res := []*Goal{}
	for {
		row, err := iter.Next()
		if err != nil {
			if err == iterator.Done {
				break
			}
			return nil, newError("FindGoalsByUserIDCreatedAt", "Goals", err)
		}

		g, err := decoder(row)
		if err != nil {
			return nil, newErrorWithCode(codes.Internal, "FindGoalsByUserIDCreatedAt", "Goals", err)
		}

		res = append(res, g)
	}

	return res, nil
}

// ReadGoalsByUserIDCreatedAt retrieves multiples rows from 'Goals' by KeySet as a slice.
//
// This does not retrieve all columns of 'Goals' because an index has only columns
// used for primary key, index key and storing columns. If you need more columns, add storing
// columns or Read by primary key or Query with join.
//
// Generated from unique index 'GoalsByUserIdCreatedAt'.
func ReadGoalsByUserIDCreatedAt(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*Goal, error) {
	var res []*Goal
	columns := []string{
		"GoalId",
		"UserId",
		"CreatedAt",
	}

	decoder := newGoal_Decoder(columns)

	rows := db.ReadUsingIndex(ctx, "Goals", "GoalsByUserIdCreatedAt", keys, columns)
	err := rows.Do(func(row *spanner.Row) error {
		g, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, g)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadGoalsByUserIDCreatedAt", "Goals", err)
	}

	return res, nil
}
