// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/akitanak/go_packaging/api/goal"
	"github.com/akitanak/go_packaging/infrastructure/inmemory"
	goal2 "github.com/akitanak/go_packaging/usecase/goal"
)

// Injectors from wire.go:

func InitializeGoalOperations() *goal.GoalOperationHandler {
	goalRepository := inmemory.NewInMemoryRepository()
	goalOperations := goal2.NewGoalOperations(goalRepository)
	goalOperationHandler := goal.NewGoalOperationHandler(goalOperations)
	return goalOperationHandler
}
